[phases.setup]
  nixPkgs = ['php82', 'php82Extensions.pdo_mysql', 'php82Extensions.gd', 'php82Extensions.zip']

[phases.install]
  cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[start]
  cmd = "apache2-foreground"
